### ISSUE TITLE
Issue booting - hv_vm_create failed

### ISSUE THREAD

**Issue by cbarratt** [mist64/xhyve#83] opened 2016-01-15 12:33 UTC
`sudo build/xhyve -A -m 4G -c 4 -s 0:0,hostbridge -s 31,lpc -l com1,stdio -s 2:1,virtio-net -f "kexec,test/vmlinuz,test/initrd.gz,earlyprintk=serial console=ttyS0"`

Results in: `hv_vm_create failed`

ProductName: Mac OS X
ProductVersion: 10.11.4
BuildVersion: 15E27e

Hardware Overview:
Model Name: MacBook Pro
Model Identifier: MacBookPro11,4
Processor Name: Intel Core i7
Processor Speed: 2.2 GHz
Number of Processors: 1
Total Number of Cores: 4
L2 Cache (per Core): 256 KB
L3 Cache: 6 MB
Memory: 16 GB
Boot ROM Version: MBP114.0172.B07
SMC Version (system): 2.29f24

**Comment by NoEffex** [comment] 2016-01-15 19:14
I am having this issue as well and it appears to be linked to 10.11.4 as it worked on 10.11.3 on my desktop and still works on 10.11.3 on my laptop.

**Comment by NoEffex** [comment] 2016-01-17 18:37
They indeed changed hypervisor.framework and I'm not certain exactly what. It is not a huge change when I did a binary diff on the library (/System/Library/Frameworks/Hypervisor.framework) but it definitely appears to have broken it. I would wager that it is Apple's fault, so I will just use the old framework until it is fixed.

**Comment by jbergstroem** [comment] 2016-01-17 22:31
@NoEffex did you file a rdar? if so, could you share it?

**Comment by AntonioMeireles** [comment] 2016-01-18 09:04
//cc @jeremyhu

**Comment by jeremyhu** [comment] 2016-01-18 21:13
File a radar at http://bugreport.apple.com and mention the radar number here.

**Comment by NoEffex** [comment] 2016-01-20 10:14
@jeremyhu I filed it under 24223377 and it was marked as a duplicate of 24073994

**Comment by jeremyhu** [comment] 2016-01-25 21:32
Should be fixed in the seed that just went out today.

**Comment by AntonioMeireles** [comment] 2016-01-25 21:40
@jeremyhu THANKS!!!!!

**Comment by 07151129** [comment] 2016-01-25 22:11
@jeremyhu By the way, are there any plans on publishing Hypervisor source in foreseeable future? :(

**Comment by cbarratt** [comment] 2016-01-26 09:18
@jeremyhu - Are you referring to a new OSX 10.11 beta seed?

**Comment by caarlos0** [comment] 2016-01-26 15:22
Same issue here.

Any workarounds?

**Comment by jeremyhu** [comment] 2016-01-26 17:02
Yes, the regression that was introduced in 10.11.4 beta seed 1 was fixed in 10.11.4 beta seed 2.  Seed 2 was released yesterday.

**Comment by zchee** [comment] 2016-01-26 17:18
@cbarratt Solved this issue on 15e33 :)

@jbergstroem Thanks fixed :)

I recorded screencast.
See
- https://asciinema.org/a/34798
- https://asciinema.org/a/34797

**Comment by caarlos0** [comment] 2016-01-27 00:26
@zchee how do I need to do to user the new version?

**Comment by zchee** [comment] 2016-01-27 00:33
@caarlos0 Sorry, I am not good at English :(
I didn't quite understand what you meant. 

Could you explain it in more detail?

**Comment by caarlos0** [comment] 2016-01-27 00:40
@zchee sorry..

as far as I understood, the issue is fixed, right? 

I was wondering what are the steps to fix it in my machine... (I am with the latest xhyve version already)

**Comment by zchee** [comment] 2016-01-27 00:52
@caarlos0 Sorry, I do not yet understand all :(
Do you still have this problem occurs?

OS X builds 15E27e has a Hypervisor bug.
OS X builds 15E33e fixed.
Did you upgrade your OS X to 15E33e (OS X El Capitan v10.11.4 beta 2)?
If you use OS X version is not 15E27e, It is not related to this problem.

>  (I am with the latest xhyve version already)

This issue is not related to the xhyve

**Comment by caarlos0** [comment] 2016-01-27 00:57
@zchee oh sorry, it's me that is messing up... I thought it was a xhyve update, but it is an OSX update... so, yeah, I need to update my OSX :package: 

sorry for the misunderstanding.

**Comment by zchee** [comment] 2016-01-27 04:34
@caarlos0 :)

**Comment by cbarratt** [comment] 2016-01-27 08:57
Annoyingly I'm on public beta rather than developer beta so I don't have any new updates :(

**Comment by caarlos0** [comment] 2016-01-27 12:09
@cbarratt yeah me neither

**Comment by Jellyfrog** [comment] 2016-01-27 23:44
Works with latest beta
ProductVersion:	10.11.4
BuildVersion:	15E33e

**Closed** 2016-03-31 04:40 UTC
