### ISSUE TITLE
Avoid kernel panic: Detect if other processes are using vmx

### ISSUE THREAD

**Issue by tiborvass** [mist64/xhyve#9] opened 2015-06-10 15:59 UTC
Currently, if you have virtualbox running already, xhyve will kernel panic.

Is there a way we could detect if something is already using vmx and error out cleanly?

**Comment by xez** [comment] 2015-06-10 16:08
I can reproduce the panic with VirtualBox + xhyve but not VMware + xhyve. Maybe only an issue with VirtualBox?

**Comment by tiborvass** [comment] 2015-06-10 16:12
@xez I am no expert on VMX but I think I read that there are two modes: one that lets other processes use VMX, and one that doesn't and I believe Virtualbox uses the latter. I believe Parallels also does that, however it has some error handling code, and will prompt to close Virtualbox.

I am not sure if folks at Parallels added virtualbox-specific code (i.e. check if Virtualbox is running) or if there is a proper way to check if we can access vmx before actually using it.

**Comment by mist64** [comment] 2015-06-10 17:43
Duplicate of https://github.com/mist64/xhyve/issues/9 - there is nothing xhyve can do, we're user mode, and this is a kernel panic. :( VirtualBox has to be fixed to play nicely with Hypervisor.framework.

**Closed by mist64** 2015-06-10 17:43 UTC

**Comment by mdaniel** [comment] 2015-06-10 17:59
I think you mean dupe of #5 and since you are well versed in Hypervisor.framework, could we implore you to search or file an issue with VirtualBox? Just saying they need to here in a GH comment does not help them achieve that goal.

**Comment by tiborvass** [comment] 2015-06-10 18:17
@mist64 FWIW, Parallels can detect that something incompatible is using vmx (here: it's xhyve).
![Parallels detecting xhyve](http://i.imgur.com/O6Vet9e.png)

**Comment by il-demone-guardiano** [comment] 2015-07-11 10:26
Does not happen anymore with VirtualBox 5.0. 
You can even run VirtualBox and xhyve side by side.

**Comment by paulp** [comment] 2015-07-11 15:13
Confirming @il-demone-guardiano's experience.

![screen shot 2015-07-11 at 08 11 13](https://cloud.githubusercontent.com/assets/9135/8634203/8f6d9240-27a4-11e5-85a8-e57b01f0a7cb.png)

**Comment by AntonioMeireles** [comment] 2015-07-11 21:11
#39 updates docs regarding this :smile:
